from .attendance import Attendance
from .batch import Batch
from .current_batches import CurrentBatches
from .faculty import Faculty
from .feedback import Feedback
from .marksheet import Marksheet
from .previous_batches import PreviousBatches
from .student import Student
from .studymaterial import StudyMaterial
from .admin import Admin
from .otp import OTP